### ISSUE TITLE
Too many plots requested

### ISSUE THREAD

**Issue by vittorione94** [google-deepmind/mujoco_mpc#105]
Hello,

If we request more than 100 plots, the GUI plots some overflows 

<img width="177" alt="Screenshot 2023-04-19 at 16 20 19" src="https://user-images.githubusercontent.com/11392217/233122734-3ab6294c-fe31-415e-944e-5f66f773c32a.png">

In the terminal I receive: `Too many plots requested: 100`

**Comment by yuvaltassa** [comment]
@thowell shouldn't it be easy to break from some loop somewhere at `mjMAXLINE` ?

**Comment by thowell** [comment]
This issue should be [fixed](https://github.com/google-deepmind/mujoco_mpc/blob/dc00a680ecd25175dad0ef8e5e6a4e1f1b22176c/mjpc/utilities.cc#L722).
