### ISSUE TITLE
support more robots

### ISSUE THREAD

**Issue by GilgameshD** [google-deepmind/mujoco_mpc#116]
Hi, thanks for building this amazing project! I wonder if there is any plan to support more robots, for example, Unitree go1, which should be very similar to A1. Thanks

**Comment by thowell** [comment]
Thanks for your interest in MJPC. If you would like to add another task, take a look at this [part](https://github.com/deepmind/mujoco_mpc/blob/main/docs/OVERVIEW.md#task-specification) of the documentation. 

It's pretty straight forward to modify the A1 task by swapping in the Go1 xml model (and the related assets) from [Menagerie](https://github.com/deepmind/mujoco_menagerie/tree/main/unitree_go1).

@kevinzakka do you have the Go1 task floating around somewhere?

**Comment by kevinzakka** [comment]
Go1 XML is now in Menagerie — it should be super straightforward to replicate the A1 task for it, mostly just a matter of copying over the XML and assets and adding some sites.

**Comment by GilgameshD** [comment]
Thanks for replying. I tried to replace A1.xml with GO1.xml and fix all compatibility problems. I can successfully start the UI with GO1 now. But the robot always flips and cannot walk. I guess there are still some parameters in the task file that are not compatible with GO1. Is there anything I should change in [this file](https://github.com/deepmind/mujoco_mpc/blob/main/mjpc/tasks/quadruped/quadruped.cc)?

**Comment by thowell** [comment]
You will likely need to change some of the parameters [here](https://github.com/deepmind/mujoco_mpc/blob/47e54222009bb454d22952c0a79d9a83c6659f01/mjpc/tasks/quadruped/quadruped.h#L121) like `kHeightQuadruped`.

**Comment by GilgameshD** [comment]
will try, thanks!

**Comment by lyuyiqi** [comment]
Hi all. I am working on a similar project and I've had GO1 working on my simulator. However, everytime I turned off "action" the robot always straightened its feet and jump off the ground (restore to its initial abduction, hip and knee angles) instead of lying down due to loss of actuation like original A1 model does. I would really appreciate it if you could give me some hint to solve this problem.

**Comment by kevinzakka** [comment]
@lyuyiqi Are you using torque or position actuators?

**Comment by lyuyiqi** [comment]
Thank you for your reply. I just checked the model again and indeed the actuators are position type. After I replace them with general type and now it works very well! Thank you again for your instruction!

**Comment by yuvaltassa** [comment]
Did you try reducing the timestep?

**Comment by fucker007** [comment]
Thanks for replying，It is work well when setting a smaller timestep.  I am learning the code of humanoid walker, but I am wondering why -7 when setting posture.   
code path: ` mujoco_mpc/tree/main/mjpc/tasks/humanoid/walk/walk.cc,  line 122. `  
```
  // ----- posture ----- //  
  mju_copy(&residual[counter], data->qpos + 7, model->nq - 7);  
  counter += model->nq - 7;  
```
@yuvaltassa thanks for your replying, best wish.

**Comment by kevinzakka** [comment]
-7 because we don't want to index the freejoint (3 dims for pos, 4 for quat).

**Comment by fucker007** [comment]
> -7 because we don't want to index the freejoint (3 dims for pos, 4 for quat).

Thanks for replying，This makes me understand correctly, bless you.

**Comment by fucker007** [comment]
I have tried some tricks on cassie , however  it's diffcult to walk by mujoco_mpc,  so  is it possible ? any suggestion, be grateful.

**Comment by thowell** [comment]
See #206 for using cassie model with MJPC.
