### ISSUE TITLE
Crash when switching from Humanoid Tracking to Humanoid Walk tasks

### ISSUE THREAD

**Issue by thowell** [google-deepmind/mujoco_mpc#134]
The GUI will crash when switching between the humanoid tracking and humanoid walking tasks. Not sure what the fix is yet.

**Comment by vicltz** [comment]
Same issue here. I tried to build my own task and crash also happen when switching to my task.

Crash is a `SIGKILL` from the system.

**Comment by thowell** [comment]
Don't see this issue anymore.
