### ISSUE TITLE
The C compiler     "/usr/bin/c++"   is not able to compile a simple test program.

### ISSUE THREAD

**Issue by lbt0116** [google-deepmind/mujoco_mpc#178]
![截图 2023-09-07 15-43-52](https://github.com/deepmind/mujoco_mpc/assets/53040132/19c84253-0bdd-4baa-ad5b-d233d5d659e4)
Hello I used clang14 to build this program but met such problem.

**Comment by thowell** [comment]
Feel free to email me to set up a video call if you have issues building and running with VSCode.
