### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by TianhongZhou** [google-deepmind/mujoco_mpc#216]
Hi, I am trying to use MuJoCo on Windows, and I followed the instruction to download a vs code, with two extensions. But this is an error that I get, is there any suggestion on how to deal with it?

![image](https://github.com/google-deepmind/mujoco_mpc/assets/93419666/90303a61-e152-4650-b717-b5e36dad79d9)

**Comment by erez-tom** [comment]
This is a known issue we're hoping to fix in a few days.  Meanwhile, take a look at #212 , #215 , and/or #214 .  If you come up with the perfect solution, please send a PR!
