### ISSUE TITLE
MuJoCo MPC running on GPU (MuJoCo XLA)

### ISSUE THREAD

**Issue by hessad** [google-deepmind/mujoco_mpc#221]
Has anyone tried to use MJPC (e.g. predictive sampling) with MuJoCo XLA to take advantage of GPU parallelization? Is it being added in future MJPC versions or could it already be tested with the current MJPC version and some modification?

**Comment by thowell** [comment]
I haven't seen an implementation of predictive sampling written in JAX, but this is definitely something of interest.

I recommend checking out [trajax](https://github.com/google/trajax) which includes a number of planners written in JAX. This tool should be compatible with MuJoCo XLA.
