### ISSUE TITLE
Bug in iLQS: dim_actions and dim_parameters not updated.

### ISSUE THREAD

**Issue by nimrod-gileadi** [google-deepmind/mujoco_mpc#264]
On [this line](https://github.com/google-deepmind/mujoco_mpc/blob/v0.0.1/mjpc/planners/ilqs/planner.cc#L120), local variables `dim_actions` and `dim_parameters` are declared, which means that the assignment doesn't affect the member variables of the same name, so they're always zero.

This has two effects:
1. Later down that function, [mju_mulMatTMat](https://github.com/google-deepmind/mujoco_mpc/blob/v0.0.1/mjpc/planners/ilqs/planner.cc#L155) is called with matrix sizes of 0, so there's no mapping from the iLQG nominal plan to the sampling nominal plan.
2. The spline mapping computation happens every time, instead of just once.

The fix is simple, removing the `int ` from the two lines. I tried it and it looks fine to me, but I saw no obvious impact on the performance of iLQS, so I wanted to check with Taylor if there's some model where this could have a significant impact, and to validate that recomputing the spline mapping is not necessary.

**Comment by thowell** [comment]
Good catch!

This change should only improve tasks that use this planner. I tried the fix and things seem good to me.
