### ISSUE TITLE
Iteration timing graph, total time confusion?

### ISSUE THREAD

**Issue by DMackRus** [google-deepmind/mujoco_mpc#271]
Hi,

On the timings graph in the bottom right, is the total time line just simply the total iteration time?

When I time the "Iteration" function, the total time for that function is a good 30 % quicker than the graph seems to imply? Is there some other timing segment I am missing that is included in total time?

**Comment by erez-tom** [comment]
I'm not sure what you mean.  The data presented in the lower right plot under the label "Total" [comes from](https://github.com/google-deepmind/mujoco_mpc/blob/main/mjpc/agent.cc#L1074) `agent_compute_time_`, which is computed [here](https://github.com/google-deepmind/mujoco_mpc/blob/main/mjpc/agent.cc#L278) by measuring the wall clock time of a single planning iteration.

Are you using some other timing mechanism?

**Comment by DMackRus** [comment]
Hello,

Oh i see, thank you!

I was just running a timer in the "Iteration" function in the planner, I didn't realise that the nominal trajectory was computed before this function. The nominal computation time takes account of the time difference.
