### ISSUE TITLE
Bug: `elite_avg` `state` field is always 0 in `cross_entropy` planner

### ISSUE THREAD

**Issue by alberthli** [google-deepmind/mujoco_mpc#282]
As per discussion in chat w/ @thowell , when querying the best trajectory from an agent running CEM, the `state` field is all 0s. A rollout for the `elite_avg` trajectory needs to be computed every planner iteration and we should either remove the resetting of `elite_avg` or place it elsewhere relative to the nominal rollout.

**Comment by thowell** [comment]
Should be fixed in #284
