### ISSUE TITLE
Loading new tasks

### ISSUE THREAD

**Issue by richardrl** [google-deepmind/mujoco_mpc#305]
Can you give an example of how to load new tasks, e.g. the manipulation task?

I can run mjpc but it runs the default locomotion task. I can't figure out how to see the command line arguments.

**Comment by thowell** [comment]
From the GUI you can change the model here:
<img width="245" alt="image" src="https://github.com/google-deepmind/mujoco_mpc/assets/12521315/6a1f83a9-76a9-4c1a-b1ca-1286f0880e75">

From the command line:
```bash
--task <Task>
```
(eg, `--task Shadow`)

**Comment by ppap36** [comment]
bro, have you successfully tried a new task?
