### ISSUE TITLE
python API FAILED: bin/agent_server FAILED: bin/ui_agent_server 

### ISSUE THREAD

**Issue by dhockingofthegods** [google-deepmind/mujoco_mpc#321]
home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ******************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try pip install --use-pep517.
        ******************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ******************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ******************************************************************************

!!
  self.initialize_options()
/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ******************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ******************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing mujoco_mpc.egg-info/PKG-INFO
writing dependency_links to mujoco_mpc.egg-info/dependency_links.txt
writing requirements to mujoco_mpc.egg-info/requires.txt
writing top-level names to mujoco_mpc.egg-info/top_level.txt
reading manifest file 'mujoco_mpc.egg-info/SOURCES.txt'
writing manifest file 'mujoco_mpc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running generate_proto_grpc
touch /home/dhocking/mjc/mujoco_mpc/python/build/lib.linux-x86_64-cpython-312/mujoco_mpc/proto/__init__.py
running copy_task_assets
copying mujoco_mpc/filter_test.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/direct.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/direct_test.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/agent.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/filter.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/ui_agent_test.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/mjpc_parameters.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/__init__.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
copying mujoco_mpc/agent_test.py -> build/lib.linux-x86_64-cpython-312/mujoco_mpc
running build_ext
Configuring CMake with the following arguments:
  -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
  -DCMAKE_BUILD_TYPE:STRING=Debug
  -DBUILD_TESTING:BOOL=OFF
  -DMJPC_BUILD_GRPC_SERVICE:BOOL=ON
CHECK_STARTmujoco::FindOrFetch: checking for targets in package mujoco
CHECK_FAILtarget mujoco::mujoco not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve mujoco
CHECK_STARTmujoco::FindOrFetch: checking for targets in package qhull
CHECK_FAILtarget qhull not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve qhull
-- 
-- ========== qhull Build Information ==========
-- Build Version:                             8.1-alpha1
-- Install Prefix (CMAKE_INSTALL_PREFIX):     /usr/local
-- Binary Directory (BIN_INSTALL_DIR):        bin
-- Library Directory (LIB_INSTALL_DIR):       lib
-- Include Directory (INCLUDE_INSTALL_DIR):   include
-- Documentation Directory (DOC_INSTALL_DIR): share/doc/qhull
-- Man Pages Directory (MAN_INSTALL_DIR):     share/man/man1
-- CMake Directory (CMAKE_INSTALL_DIR):       lib/cmake/QHull
-- PkgConfig Directory (PKGCONFIG_INSTALL_DIR):lib/pkgconfig
-- Build Type (CMAKE_BUILD_TYPE):             Debug
-- Build static libraries:                    ON
-- Build shared library:                      OFF
-- Use shared library for linking apps:       OFF
-- Build tests:				   OFF
-- To override these options, add -D{OPTION_NAME}=... to the cmake command
--   Build the debug targets                  -DCMAKE_BUILD_TYPE=Debug
-- 
-- To build and install qhull, enter "make" and "make install"
-- To smoketest qhull, enter "ctest"
-- 
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package tinyxml2
CHECK_FAILtarget tinyxml2 not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve tinyxml2
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package tinyobjloader
CHECK_FAILtarget tinyobjloader not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve tinyobjloader
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package sdflib
CHECK_FAILtarget SdfLib not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve sdflib
-- GLM is a header only library, no need to build it. Set the option GLM_TEST_ENABLE with ON to build and run the test bench
-- Build spdlog: 1.9.2
-- Build type: Debug
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package ccd
CHECK_FAILtarget ccd not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve ccd
CMake Warning (dev) at build/_deps/ccd-src/CMakeLists.txt:9 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package mujoco
CHECK_PASSfound
CHECK_STARTmujoco::FindOrFetch: checking for targets in package glfw3
CHECK_FAILtarget glfw not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve glfw3
-- Using X11 for window creation
CHECK_PASSDone
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package GTest
CHECK_FAILtarget gtest not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve googletest
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package absl
CHECK_FAILtarget absl::core_headers not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve abseil-cpp
CHECK_PASSDone
CHECK_STARTmujoco::FindOrFetch: checking for targets in package glfw
CHECK_PASSfound
CHECK_STARTmujoco::FindOrFetch: checking for targets in package gRPC
CHECK_FAILtarget gRPC not defined.
CHECK_STARTmujoco::FindOrFetch: Using FetchContent to retrieve gRPC
-- 
-- 25.0.0
-- Checking for module 'libsystemd>=233'
--   No package 'libsystemd' found
CHECK_PASSDone
We need the following for agent/direct_protos:
_GRPC_CPP_PLUGIN_EXECUTABLE$<TARGET_FILE:grpc_cpp_plugin>
AGENT_SERVICE_COMPILE_OPTIONS=
AGENT_SERVICE_COMPILE_OPTIONS=
DIRECT_SERVICE_COMPILE_OPTIONS=
FILTER_SERVICE_COMPILE_OPTIONS=
-- Configuring done
CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/lib/CMakeLists.txt:72 (ADD_LIBRARY):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "c-ares" of type "STATIC_LIBRARY" has the following visibility
  properties set for C:

    C_VISIBILITY_PRESET

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/tools/CMakeLists.txt:41 (ADD_EXECUTABLE):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "acountry" of type "EXECUTABLE" has the following visibility
  properties set for C:

    C_VISIBILITY_PRESET

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/tools/CMakeLists.txt:24 (ADD_EXECUTABLE):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "adig" of type "EXECUTABLE" has the following visibility properties
  set for C:

    C_VISIBILITY_PRESET

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/_deps/grpc-src/third_party/cares/cares/src/tools/CMakeLists.txt:7 (ADD_EXECUTABLE):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "ahost" of type "EXECUTABLE" has the following visibility properties
  set for C:

    C_VISIBILITY_PRESET

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/dhocking/mjc/mujoco_mpc/build
Building agent_server and ui_agent_server with CMake
[0/2] Re-checking globbed directories...
[2/6] Copying Menagerie and dm_control assets into binary directory
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/acrobot/acrobot_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/acrobot/acrobot.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/cartpole/cartpole_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/cartpole/cartpole.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/humanoid/humanoid_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/humanoid/humanoid.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/particle/particle_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/particle/particle.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/swimmer/swimmer_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/swimmer/swimmer.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/walker/walker_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/walker/walker.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/allegro/right_hand_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/allegro/right_hand.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/panda/panda_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/panda/panda.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/quadruped/a1_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/quadruped/a1.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/quadrotor/quadrotor_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/quadrotor/quadrotor.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/common_assets/cube_modified_shadow_reorient.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/common_assets/reorientation_cube.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/rubik/cube_3x3x3_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/rubik/cube_3x3x3.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/rubik/transition_model.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/rubik/cube_3x3x3.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/aloha_cartesian.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/aloha.xml)
Hunk #2 succeeded at 286 (offset 2 lines).
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/mjx_aloha.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/aloha.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/mjx_scene.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/scene.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/mjx_integrated_cartesian_actuators.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/bimanual/integrated_cartesian_actuators.xml)
patching file /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/op3/op3_modified.xml (read from /home/dhocking/mjc/mujoco_mpc/build/mjpc/tasks/op3/op3.xml)
[5/6] Linking CXX executable bin/agent_server
FAILED: bin/agent_server 
: && /usr/bin/clang++-12  -g   mjpc/grpc/CMakeFiles/agent_server.dir/agent_server.cc.o  -o bin/agent_server  -Wl,-rpath,/home/dhocking/mjc/mujoco_mpc/build/lib  lib/libmjpc_agent_service.a  lib/libabsl_flags.a  lib/libabsl_flags_parse.a  lib/libabsl_status.a  lib/libabsl_strings.a  lib/libgrpc++_reflection.a  lib/libgrpc++.a  lib/libprotobufd.a  lib/libmjpc.a  lib/libglfw3.a  /usr/lib/x86_64-linux-gnu/librt.so  -lm  /usr/lib/x86_64-linux-gnu/libX11.so  lib/liblodepng.a  lib/libmujoco.so.3.1.3  lib/libthreadpool.a  lib/libagent_service_proto_lib.a  lib/libgrpc++_reflection.a  lib/libgrpc++.a  lib/libgrpc.a  lib/libupb_collections_lib.a  lib/libupb_json_lib.a  lib/libupb_textformat_lib.a  lib/libutf8_range_lib.a  lib/libupb.a  lib/libre2.a  /usr/lib/x86_64-linux-gnu/libz.so  _deps/grpc-build/third_party/cares/cares/lib/libcares.a  lib/libgpr.a  lib/libssl.a  lib/libcrypto.a  lib/libaddress_sorting.a  -ldl  -lm  -lrt  lib/libprotobufd.a  lib/libabsl_log_internal_check_op.a  lib/libabsl_leak_check.a  lib/libabsl_die_if_null.a  lib/libabsl_log_internal_conditions.a  lib/libabsl_log_internal_message.a  lib/libabsl_log_internal_nullguard.a  lib/libabsl_examine_stack.a  lib/libabsl_log_internal_format.a  lib/libabsl_log_internal_proto.a  lib/libabsl_log_internal_log_sink_set.a  lib/libabsl_log_sink.a  lib/libabsl_log_entry.a  lib/libabsl_log_initialize.a  lib/libabsl_log_internal_globals.a  lib/libabsl_log_globals.a  lib/libabsl_statusor.a  lib/libabsl_status.a  lib/libabsl_strerror.a  lib/libutf8_validity.a  lib/libabsl_random_distributions.a  lib/libabsl_random_seed_sequences.a  lib/libabsl_random_internal_pool_urbg.a  lib/libabsl_random_internal_randen.a  lib/libabsl_random_internal_randen_hwaes.a  lib/libabsl_random_internal_randen_hwaes_impl.a  lib/libabsl_random_internal_randen_slow.a  lib/libabsl_random_internal_platform.a  lib/libabsl_random_internal_seed_material.a  lib/libabsl_random_seed_gen_exception.a  lib/libabsl_flags_usage.a  lib/libabsl_flags_usage_internal.a  lib/libabsl_flags.a  lib/libabsl_flags_internal.a  lib/libabsl_flags_marshalling.a  lib/libabsl_flags_reflection.a  lib/libabsl_flags_config.a  lib/libabsl_flags_private_handle_accessor.a  lib/libabsl_flags_commandlineflag.a  lib/libabsl_flags_commandlineflag_internal.a  lib/libabsl_flags_program_name.a  lib/libabsl_cord.a  lib/libabsl_cordz_info.a  lib/libabsl_cord_internal.a  lib/libabsl_cordz_functions.a  lib/libabsl_cordz_handle.a  lib/libabsl_crc_cord_state.a  lib/libabsl_crc32c.a  lib/libabsl_str_format_internal.a  lib/libabsl_crc_internal.a  lib/libabsl_crc_cpu_detect.a  lib/libabsl_raw_hash_set.a  lib/libabsl_hash.a  lib/libabsl_bad_optional_access.a  lib/libabsl_bad_variant_access.a  lib/libabsl_city.a  lib/libabsl_low_level_hash.a  lib/libabsl_hashtablez_sampler.a  lib/libabsl_exponential_biased.a  lib/libabsl_synchronization.a  lib/libabsl_stacktrace.a  lib/libabsl_symbolize.a  lib/libabsl_debugging_internal.a  lib/libabsl_demangle_internal.a  lib/libabsl_graphcycles_internal.a  lib/libabsl_kernel_timeout_internal.a  lib/libabsl_time.a  lib/libabsl_strings.a  lib/libabsl_string_view.a  lib/libabsl_strings_internal.a  lib/libabsl_throw_delegate.a  lib/libabsl_int128.a  lib/libabsl_civil_time.a  lib/libabsl_time_zone.a  lib/libabsl_malloc_internal.a  lib/libabsl_base.a  lib/libabsl_spinlock_wait.a  -lrt  lib/libabsl_raw_logging_internal.a  lib/libabsl_log_severity.a  -pthread && :
/usr/bin/ld: lib/libmujoco.so.3.1.3: undefined reference to `__muloti4'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[6/6] Linking CXX executable bin/ui_agent_server
FAILED: bin/ui_agent_server 
: && /usr/bin/clang++-12  -g   _deps/mujoco-build/simulate/CMakeFiles/platform_ui_adapter.dir/glfw_adapter.cc.o _deps/mujoco-build/simulate/CMakeFiles/platform_ui_adapter.dir/glfw_dispatch.cc.o _deps/mujoco-build/simulate/CMakeFiles/platform_ui_adapter.dir/platform_ui_adapter.cc.o mjpc/grpc/CMakeFiles/ui_agent_server.dir/ui_agent_server.cc.o  -o bin/ui_agent_server  -Wl,-rpath,/home/dhocking/mjc/mujoco_mpc/build/lib  lib/libmjpc_ui_agent_service.a  lib/libgrpc++.a  lib/libprotobufd.a  lib/libgrpc++_reflection.a  lib/libabsl_flags.a  lib/libabsl_flags_parse.a  lib/libabsl_status.a  lib/libabsl_strings.a  lib/libglfw3.a  lib/libmjpc.a  lib/libglfw3.a  /usr/lib/x86_64-linux-gnu/librt.so  -lm  /usr/lib/x86_64-linux-gnu/libX11.so  lib/liblodepng.a  lib/libmujoco.so.3.1.3  lib/libagent_service_proto_lib.a  lib/libgrpc++_reflection.a  lib/libgrpc++.a  lib/libprotobufd.a  lib/libabsl_leak_check.a  lib/libabsl_die_if_null.a  lib/libabsl_log_initialize.a  lib/libutf8_validity.a  lib/libgrpc.a  lib/libabsl_statusor.a  lib/libupb_collections_lib.a  lib/libupb_json_lib.a  lib/libupb_textformat_lib.a  lib/libutf8_range_lib.a  lib/libupb.a  lib/libre2.a  /usr/lib/x86_64-linux-gnu/libz.so  _deps/grpc-build/third_party/cares/cares/lib/libcares.a  lib/libgpr.a  lib/libabsl_status.a  lib/libabsl_random_distributions.a  lib/libabsl_random_seed_sequences.a  lib/libabsl_random_internal_pool_urbg.a  lib/libabsl_random_internal_randen.a  lib/libabsl_random_internal_randen_hwaes.a  lib/libabsl_random_internal_randen_hwaes_impl.a  lib/libabsl_random_internal_randen_slow.a  lib/libabsl_random_internal_platform.a  lib/libabsl_random_internal_seed_material.a  lib/libabsl_random_seed_gen_exception.a  lib/libssl.a  lib/libcrypto.a  lib/libaddress_sorting.a  -ldl  -lm  -lrt  lib/libabsl_log_internal_check_op.a  lib/libabsl_log_internal_conditions.a  lib/libabsl_log_internal_message.a  lib/libabsl_strerror.a  lib/libabsl_log_internal_nullguard.a  lib/libabsl_examine_stack.a  lib/libabsl_log_internal_format.a  lib/libabsl_log_internal_proto.a  lib/libabsl_log_internal_log_sink_set.a  lib/libabsl_log_globals.a  lib/libabsl_log_internal_globals.a  lib/libabsl_log_sink.a  lib/libabsl_log_entry.a  lib/libthreadpool.a  lib/libabsl_flags_usage.a  lib/libabsl_flags_usage_internal.a  lib/libabsl_flags.a  lib/libabsl_flags_internal.a  lib/libabsl_flags_marshalling.a  lib/libabsl_flags_reflection.a  lib/libabsl_cord.a  lib/libabsl_cordz_info.a  lib/libabsl_cord_internal.a  lib/libabsl_cordz_functions.a  lib/libabsl_cordz_handle.a  lib/libabsl_crc_cord_state.a  lib/libabsl_crc32c.a  lib/libabsl_str_format_internal.a  lib/libabsl_crc_internal.a  lib/libabsl_crc_cpu_detect.a  lib/libabsl_raw_hash_set.a  lib/libabsl_hash.a  lib/libabsl_bad_variant_access.a  lib/libabsl_city.a  lib/libabsl_low_level_hash.a  lib/libabsl_hashtablez_sampler.a  lib/libabsl_exponential_biased.a  lib/libabsl_flags_config.a  lib/libabsl_flags_private_handle_accessor.a  lib/libabsl_flags_commandlineflag.a  lib/libabsl_bad_optional_access.a  lib/libabsl_flags_commandlineflag_internal.a  lib/libabsl_flags_program_name.a  lib/libabsl_synchronization.a  lib/libabsl_stacktrace.a  lib/libabsl_symbolize.a  lib/libabsl_debugging_internal.a  lib/libabsl_demangle_internal.a  lib/libabsl_graphcycles_internal.a  lib/libabsl_kernel_timeout_internal.a  lib/libabsl_time.a  lib/libabsl_civil_time.a  lib/libabsl_time_zone.a  lib/libabsl_malloc_internal.a  lib/libabsl_strings.a  lib/libabsl_string_view.a  lib/libabsl_strings_internal.a  lib/libabsl_base.a  -pthread  lib/libabsl_spinlock_wait.a  -lrt  lib/libabsl_int128.a  lib/libabsl_throw_delegate.a  lib/libabsl_raw_logging_internal.a  lib/libabsl_log_severity.a && :
/usr/bin/ld: lib/libmujoco.so.3.1.3: undefined reference to `__muloti4'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/dhocking/mjc/mujoco_mpc/python/setup.py", line 248, in <module>
    setuptools.setup(
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/command/install.py", line 87, in run
    self.do_egg_install()
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dhocking/mjc/mujoco_mpc/python/setup.py", line 191, in run
    self._configure_and_build_agent_server()
  File "/home/dhocking/mjc/mujoco_mpc/python/setup.py", line 232, in _configure_and_build_agent_server
    subprocess.check_call(
  File "/home/dhocking/anaconda3/envs/env1_3_11/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/dhocking/mjc/mujoco_mpc/build', '--target', 'agent_server', 'ui_agent_server', '-j8', '--config', 'Debug']' returned non-zero exit status 1.
I can run the GUI but when i type
python setup.py install it have some issue like that
[5/6] Linking CXX executable bin/agent_server
FAILED: bin/agent_server 
[6/6] Linking CXX executable bin/ui_agent_server
FAILED: bin/ui_agent_server 
i have fix this bug for 4 days and have no ideal what to do to fix this

**Comment by dhockingofthegods** [comment]
i have fix this bug, i upgrade ubuntu 20.04 to 22.04 and use clang-14

**Comment by thowell** [comment]
Please see improved installation instructions: #324
