### ISSUE TITLE
why action controll residuals are crucial?

### ISSUE THREAD

**Issue by MyelinsheathXD** [google-deepmind/mujoco_mpc#329]
hey folks!
I have been trying to optimize humanoid task with minimizing residual count.
I have changed controll resuals with 2 ways
1-totally removing the action  control residuals
2- combining all action control residuals into one variable residual

both ways made the iLQG to fail.
My question : Is there way to decrese residual count of action controll and keep the optimizer as  stable as possible?
if not why?

**Comment by yuvaltassa** [comment]
No. See equation 5b [here](https://homes.cs.washington.edu/~todorov/papers/TassaICRA14.pdf).
iLQG need a positive definite Quu.
