### ISSUE TITLE
Different behavior between python API and GUI

### ISSUE THREAD

**Issue by adawne** [google-deepmind/mujoco_mpc#347]
Hi! Thank you for this work! I was able to achieve the task I wanted using the GUI. However, I noticed that when I tried using the Python API with the exact same setup, I ended up with a different trajectory. I need to use the Python API because I have to integrate it with another part that is already implemented in MuJoCo using Python.

Could this difference in behavior be related to this issue? [https://github.com/google-deepmind/mujoco_mpc/issues/322#issuecomment-2111497018](url). Do you have any tips on how I can achieve the same behavior in Python as I do in the GUI? Also, the MPC parameters defined in the MJCF file should be automatically applied when I run the model in Python, correct?

**Comment by thowell** [comment]
The C++ GUI interface is asynchronous. The number of planning iterations per simulation step is hardware dependent. In contrast, the Python API is synchronous and the number of planning iterations per simulation step is fixed. 

Increasing the number of planning iterations per simulation step should be beneficial. For example, in this [cartpole demo](https://github.com/google-deepmind/mujoco_mpc/blob/1f78168912b4fe4af30365198c9f4e3ecf025ba1/python/mujoco_mpc/demos/agent/cartpole.py#L96) increase `num_steps`.

The C++ interface and Python API use the same parameters and settings defined in the task xml file.
