### ISSUE TITLE
How to Access Planner Internal States (e.g., K Matrix in iLQR) via Python

### ISSUE THREAD

**Issue by jc-bao** [google-deepmind/mujoco_mpc#365]
To retrieve the planned action, I can use `agent.get_action()`. However, I would like to access the internal states of the planner, such as the K matrix in iLQR.
Is there a Python protocol or recommended way to access these internal states?
Thanks!

**Comment by thowell** [comment]
Planner specific internal states are not currently provided by the [Python API](https://github.com/google-deepmind/mujoco_mpc/blob/main/python/mujoco_mpc/agent.py).

**Comment by jc-bao** [comment]
Got it. Thanks!
