### ISSUE TITLE
How to update Mujoco version of mjpc?

### ISSUE THREAD

**Issue by ppap36** [google-deepmind/mujoco_mpc#366]
Hello, I am a student from BIT, and I plan to use the features of Mujoco 3.2.3.
Can I manually update the mujoco version of mjpc?
What potential bugs might occur?

Thank you !

**Comment by yuvaltassa** [comment]
Yes, just do something like this: 230bbb58d19a81ee649490f8ea6aa464bfa3eb0a
Re bugs – try and find out!
