### ISSUE TITLE
Pipe crawler robot simulation and control system development for small diameter pipes

### ISSUE THREAD

**Issue by robinsarkerme** [google-deepmind/mujoco_mpc#98]
I would like to open this issue to get help on developing a control strategy and virtual simulation of a pipe inspection robot that will navigate through a small diameter pipe. Developing the control strategy for controlling the robot's motion is challenging and I have been working on it for a while. 

How can I get help and start working on it collaboratively? Thanks

**Comment by thowell** [comment]
Sounds like an interesting project. Can you share your current model (.xml) and describe in more detail the behavior for the inspection robot?
